RawZone:
  dataset_1 : '../Raw Zone/dataset_sample_1.csv'
  dataset_2 : '../Raw Zone/dataset_sample_2.csv'
StagingZone:
  dataset_1: '../Staging Zone/dataset_sample_1.csv'
  dataset_2: '../Staging Zone/dataset_sample_2.csv'
  productos: '../Staging Zone/productos.csv'
  user_item_matrix: '../Staging Zone/user_item_matrix.parquet'
TrustZone:
  PCA_UBCF : '../Trusted Zone/PCA_UBCF.csv'
  PCA_IBCF : '../Trusted Zone/PCA_IBCF.csv'
  CS_IBCF : '../Trusted Zone/CS_IBCF.parquet'
Test:
  AB_TEST_DETAIL : '../Test A-B/Detalle.csv'
  AB_TEST_RESUM : '../Test A-B/Resumen.csv'